# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1
orbs:
  heroku: circleci/heroku@1.0.0
jobs:
  test:
    docker:
      - image: circleci/node:10.15.1
    steps:
      - checkout
      - run:
          name: Test
          command: |
            echo Building
            yarn install
            echo Testing  
            yarn test
  deploy:
    executor: heroku/default # Uses the basic buildpack-deps image, which has the prerequisites for installing heroku's CLI.
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git:
          only-branch: master

workflows:
  version: 2.1
  test-and-deploy:
    jobs:
      - test:
        filters:
          branches:
            only: master
      - deploy:
        requires:
          - test 
        executor: heroku/default
