# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1
orbs:
  heroku: circleci/heroku@0.0.6
jobs:
  run-tests:
    docker:
      - image: circleci/node:10.15.1
    steps:
      - checkout
      - run:
          name: Test
          command: |
            echo Building
            yarn install
            echo Testing  
            yarn test
  do-something:
    docker:
      - image: circleci/node:10.15.1
    steps:
      - checkout
      - run:
          name: DoSomething
          command: |
            echo Something

workflows:
  version: 2.1
  build-deploy:
    jobs:
      - run-tests
      - heroku/deploy-via-git:
          requires:
            - run-tests
          filters:
            branches:
              only: master
