# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1
orbs:
  heroku: circleci/heroku@1.0.0
jobs:
  run-tests:
    docker:
      - image: circleci/node:10.15.1
    steps:
      - checkout
      - run:
          name: Test
          command: |
            echo Building
            yarn install
            echo Testing  
            yarn test
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - run:
        name: Boo
        command: |
          echo Hello World

workflows:
  version: 2.1
  test-and-deploy:
    jobs:
      - run-tests:
        filters:
          branches:
            only: master
      - deploy:
        requires:
          - run-tests

